name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarcLoud warning of Shallowclones
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Clean with Maven
        run: mvn clean
      - name: Compile with Maven
        run: mvn compile
      - name: Create database with sql file
        run: mysql –uroot -p < sql/create-proyectosdb.sql
      - name: Enhance with datanucleus
        run: mvn datanucleus:enhance
      - name: Create tables with datanucleus
        run: mvn datanucleus:schema-create
      - name: Execute tests
        run: mvn test
      - name: Execute Server 
        run: mvn jetty:run
      - name: Upload report to Codecov with Jacoco #Upload coverage report from JaCoCo to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Josu-Jon/Proyecto_PSC
      - name: Scan with SonarCloud #Scan with SonarCloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Josu-Jon_Proyecto_PSC