name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarcLoud warning of Shallowclones
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Run the Maven Test phase
        run: mvn -B test
      - name: Upload report to Codecov with Jacoco #Upload coverage report from JaCoCo to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Josu-Jon/Proyecto_PSC
      - name: Scan with SonarCloud #Scan with SonarCloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Josu-Jon_Proyecto_PSC