name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarcLoud warning of Shallowclones
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - name: create database in mysql-server
        run: mysql -uroot -h0.0.0.0 < sql/create-proyectosdb.sql
      - name: compile the code
        run: mvn clean compile
      - name: Create Datanucleus enhance
        run: mvn datanucleus:enhance
      - name: Create Datanucleus schema
        run: mvn datanucleus:schema-create
      - name: Run the Maven test phase
        run: mvn test
      - name: Launch the server in background mode 
        run: mvn jetty:run &
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Launch the client
        run: mvn exec:java -Pclient
      - name: Upload report to Codecov with Jacoco #Upload coverage report from JaCoCo to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Josu-Jon/Proyecto_PSC
      - name: Scan with SonarCloud #Scan with SonarCloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Josu-Jon_Proyecto_PSC